// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: evmos/cronjobs/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// RegisterCronjob
type MsgRegisterCronjob struct {
	// Cronjob
	Cronjob Cronjob `protobuf:"bytes,1,opt,name=cronjob,proto3" json:"cronjob"`
	// EOA/contract hex address
	Sender string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (m *MsgRegisterCronjob) Reset()         { *m = MsgRegisterCronjob{} }
func (m *MsgRegisterCronjob) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterCronjob) ProtoMessage()    {}
func (*MsgRegisterCronjob) Descriptor() ([]byte, []int) {
	return fileDescriptor_df05f79c94987e08, []int{0}
}
func (m *MsgRegisterCronjob) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterCronjob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterCronjob.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterCronjob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterCronjob.Merge(m, src)
}
func (m *MsgRegisterCronjob) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterCronjob) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterCronjob.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterCronjob proto.InternalMessageInfo

func (m *MsgRegisterCronjob) GetCronjob() Cronjob {
	if m != nil {
		return m.Cronjob
	}
	return Cronjob{}
}

func (m *MsgRegisterCronjob) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

// MsgConvertCoinResponse returns no fields
type MsgRegisterCronjobResponse struct {
}

func (m *MsgRegisterCronjobResponse) Reset()         { *m = MsgRegisterCronjobResponse{} }
func (m *MsgRegisterCronjobResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterCronjobResponse) ProtoMessage()    {}
func (*MsgRegisterCronjobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df05f79c94987e08, []int{1}
}
func (m *MsgRegisterCronjobResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterCronjobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterCronjobResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterCronjobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterCronjobResponse.Merge(m, src)
}
func (m *MsgRegisterCronjobResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterCronjobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterCronjobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterCronjobResponse proto.InternalMessageInfo

// MsgCancelCronjob
type MsgCancelCronjob struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Sender     string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (m *MsgCancelCronjob) Reset()         { *m = MsgCancelCronjob{} }
func (m *MsgCancelCronjob) String() string { return proto.CompactTextString(m) }
func (*MsgCancelCronjob) ProtoMessage()    {}
func (*MsgCancelCronjob) Descriptor() ([]byte, []int) {
	return fileDescriptor_df05f79c94987e08, []int{2}
}
func (m *MsgCancelCronjob) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelCronjob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelCronjob.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelCronjob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelCronjob.Merge(m, src)
}
func (m *MsgCancelCronjob) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelCronjob) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelCronjob.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelCronjob proto.InternalMessageInfo

func (m *MsgCancelCronjob) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *MsgCancelCronjob) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

// MsgConvertCoinResponse returns no fields
type MsgCancelCronjobResponse struct {
}

func (m *MsgCancelCronjobResponse) Reset()         { *m = MsgCancelCronjobResponse{} }
func (m *MsgCancelCronjobResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCancelCronjobResponse) ProtoMessage()    {}
func (*MsgCancelCronjobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df05f79c94987e08, []int{3}
}
func (m *MsgCancelCronjobResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelCronjobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelCronjobResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelCronjobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelCronjobResponse.Merge(m, src)
}
func (m *MsgCancelCronjobResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelCronjobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelCronjobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelCronjobResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterCronjob)(nil), "evmos.cronjobs.v1.MsgRegisterCronjob")
	proto.RegisterType((*MsgRegisterCronjobResponse)(nil), "evmos.cronjobs.v1.MsgRegisterCronjobResponse")
	proto.RegisterType((*MsgCancelCronjob)(nil), "evmos.cronjobs.v1.MsgCancelCronjob")
	proto.RegisterType((*MsgCancelCronjobResponse)(nil), "evmos.cronjobs.v1.MsgCancelCronjobResponse")
}

func init() { proto.RegisterFile("evmos/cronjobs/v1/tx.proto", fileDescriptor_df05f79c94987e08) }

var fileDescriptor_df05f79c94987e08 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4a, 0x02, 0x41,
	0x18, 0xc7, 0x77, 0x2c, 0x0c, 0x27, 0xa2, 0x5a, 0x22, 0x64, 0x90, 0x55, 0xac, 0x44, 0xc8, 0x76,
	0xd0, 0x3a, 0x75, 0x54, 0xe8, 0x10, 0x78, 0xd9, 0x63, 0x97, 0x58, 0xd7, 0x69, 0x9c, 0xd0, 0x99,
	0x65, 0x67, 0x5a, 0xec, 0xda, 0x0b, 0x14, 0x74, 0xe8, 0x39, 0x7a, 0x0b, 0x8f, 0x42, 0x97, 0x4e,
	0x11, 0xda, 0x83, 0x44, 0xeb, 0xac, 0xa5, 0xbb, 0x81, 0xb7, 0x6f, 0xe7, 0xfb, 0xff, 0xbf, 0xff,
	0xef, 0x9b, 0x1d, 0x88, 0x48, 0x38, 0x10, 0x12, 0x7b, 0x81, 0xe0, 0xb7, 0xa2, 0x23, 0x71, 0x58,
	0xc7, 0x6a, 0x68, 0xfb, 0x81, 0x50, 0xc2, 0xdc, 0x8d, 0x7a, 0x76, 0xdc, 0xb3, 0xc3, 0x3a, 0x2a,
	0x50, 0x21, 0x68, 0x9f, 0x60, 0xd7, 0x67, 0xd8, 0xe5, 0x5c, 0x28, 0x57, 0x31, 0xc1, 0xe5, 0xcc,
	0x80, 0xf6, 0xa8, 0xa0, 0x22, 0x2a, 0xf1, 0x4f, 0xa5, 0x4f, 0x8b, 0xc9, 0x08, 0x5d, 0xcf, 0x04,
	0xe5, 0x1e, 0x34, 0xdb, 0x92, 0x3a, 0x84, 0x32, 0xa9, 0x48, 0xd0, 0x9a, 0xf5, 0xcc, 0x73, 0xb8,
	0xa1, 0x65, 0x79, 0x50, 0x02, 0xd5, 0xcd, 0x06, 0xb2, 0x13, 0x3c, 0xb6, 0x16, 0x37, 0xd7, 0x47,
	0x1f, 0x45, 0xc3, 0x89, 0x0d, 0xe6, 0x3e, 0xcc, 0x4a, 0xc2, 0xbb, 0x24, 0xc8, 0x67, 0x4a, 0xa0,
	0x9a, 0x73, 0xf4, 0x57, 0xb9, 0x00, 0x51, 0x32, 0xc9, 0x21, 0xd2, 0x17, 0x5c, 0x92, 0xf2, 0x25,
	0xdc, 0x69, 0x4b, 0xda, 0x72, 0xb9, 0x47, 0xfa, 0x31, 0x85, 0x05, 0x21, 0xeb, 0x12, 0xae, 0xd8,
	0x0d, 0x23, 0x41, 0x04, 0x92, 0x73, 0xfe, 0x9c, 0xfc, 0x9b, 0x84, 0x60, 0x7e, 0x79, 0x56, 0x9c,
	0xd3, 0x78, 0xcd, 0xc0, 0xb5, 0xb6, 0xa4, 0xe6, 0x0b, 0x80, 0xdb, 0xcb, 0x5b, 0x1f, 0xa5, 0x2c,
	0x99, 0x44, 0x46, 0x27, 0x2b, 0xc9, 0xe6, 0x9b, 0xd9, 0x0f, 0x6f, 0x5f, 0xcf, 0x99, 0xaa, 0x59,
	0xc1, 0x69, 0xbf, 0x1b, 0x07, 0xda, 0x76, 0x1d, 0xdf, 0xdf, 0x23, 0x80, 0x5b, 0x8b, 0xf7, 0x70,
	0x90, 0x1e, 0xb8, 0x20, 0x42, 0xc7, 0x2b, 0x88, 0xe6, 0x4c, 0xb5, 0x88, 0xa9, 0x62, 0x1e, 0xa6,
	0x33, 0x79, 0x91, 0x29, 0x26, 0x6a, 0x5e, 0x8c, 0x26, 0x16, 0x18, 0x4f, 0x2c, 0xf0, 0x39, 0xb1,
	0xc0, 0xd3, 0xd4, 0x32, 0xc6, 0x53, 0xcb, 0x78, 0x9f, 0x5a, 0xc6, 0x55, 0x8d, 0x32, 0xd5, 0xbb,
	0xeb, 0xd8, 0x9e, 0x18, 0x60, 0xd5, 0x73, 0x03, 0xc9, 0xa4, 0x9e, 0x18, 0x9e, 0xe1, 0xe1, 0xef,
	0x58, 0x75, 0xef, 0x13, 0xd9, 0xc9, 0x46, 0x4f, 0xee, 0xf4, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x00,
	0xe8, 0x36, 0xa8, 0xf8, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// RegisterCronjob
	RegisterCronjob(ctx context.Context, in *MsgRegisterCronjob, opts ...grpc.CallOption) (*MsgRegisterCronjobResponse, error)
	// CancelCronjob
	CancelCronjob(ctx context.Context, in *MsgCancelCronjob, opts ...grpc.CallOption) (*MsgCancelCronjobResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterCronjob(ctx context.Context, in *MsgRegisterCronjob, opts ...grpc.CallOption) (*MsgRegisterCronjobResponse, error) {
	out := new(MsgRegisterCronjobResponse)
	err := c.cc.Invoke(ctx, "/evmos.cronjobs.v1.Msg/RegisterCronjob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelCronjob(ctx context.Context, in *MsgCancelCronjob, opts ...grpc.CallOption) (*MsgCancelCronjobResponse, error) {
	out := new(MsgCancelCronjobResponse)
	err := c.cc.Invoke(ctx, "/evmos.cronjobs.v1.Msg/CancelCronjob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// RegisterCronjob
	RegisterCronjob(context.Context, *MsgRegisterCronjob) (*MsgRegisterCronjobResponse, error)
	// CancelCronjob
	CancelCronjob(context.Context, *MsgCancelCronjob) (*MsgCancelCronjobResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterCronjob(ctx context.Context, req *MsgRegisterCronjob) (*MsgRegisterCronjobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterCronjob not implemented")
}
func (*UnimplementedMsgServer) CancelCronjob(ctx context.Context, req *MsgCancelCronjob) (*MsgCancelCronjobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelCronjob not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterCronjob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterCronjob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterCronjob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evmos.cronjobs.v1.Msg/RegisterCronjob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterCronjob(ctx, req.(*MsgRegisterCronjob))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelCronjob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelCronjob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelCronjob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evmos.cronjobs.v1.Msg/CancelCronjob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelCronjob(ctx, req.(*MsgCancelCronjob))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "evmos.cronjobs.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterCronjob",
			Handler:    _Msg_RegisterCronjob_Handler,
		},
		{
			MethodName: "CancelCronjob",
			Handler:    _Msg_CancelCronjob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evmos/cronjobs/v1/tx.proto",
}

func (m *MsgRegisterCronjob) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterCronjob) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterCronjob) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Cronjob.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgRegisterCronjobResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterCronjobResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterCronjobResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCancelCronjob) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelCronjob) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelCronjob) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Identifier) > 0 {
		i -= len(m.Identifier)
		copy(dAtA[i:], m.Identifier)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Identifier)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelCronjobResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelCronjobResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelCronjobResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterCronjob) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Cronjob.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterCronjobResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCancelCronjob) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Identifier)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCancelCronjobResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterCronjob) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterCronjob: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterCronjob: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cronjob", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Cronjob.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterCronjobResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterCronjobResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterCronjobResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelCronjob) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelCronjob: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelCronjob: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Identifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Identifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelCronjobResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelCronjobResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelCronjobResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
